# Form implementation generated from reading ui file 'E:\Ml_in_BA\Final\MlInBA_FinalProject\View\DashboardOverviewPage.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from Service.KPICardService import KPICard, KPIData


class Ui_DashboardOverviewPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(1060, 500)
        self.gridLayout = QtWidgets.QGridLayout(WizardPage)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_kpis_03 = KPICard(KPIData(value=50, unit="Total Quantity", icon_path=""))
        self.frame_kpis_03.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_kpis_03.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_kpis_03.setObjectName("frame_kpis_03")
        self.gridLayout_2.addWidget(self.frame_kpis_03, 0, 2, 1, 1)
        self.frame_kpis_01 = KPICard(KPIData(value=50, unit="Total Sales (USD)", icon_path=""))
        self.frame_kpis_01.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_kpis_01.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_kpis_01.setObjectName("frame_kpis_01")
        self.gridLayout_2.addWidget(self.frame_kpis_01, 0, 0, 1, 1)
        self.frame_kpis_02 = KPICard(KPIData(value=50, unit="Nmber of Order", icon_path=""))
        self.frame_kpis_02.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_kpis_02.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_kpis_02.setObjectName("frame_kpis_02")
        self.gridLayout_2.addWidget(self.frame_kpis_02, 0, 1, 1, 1)
        self.frame_kpis_04 = KPICard(KPIData(value=50, unit="Fulfillment Rate %", icon_path=""))
        self.frame_kpis_04.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_kpis_04.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_kpis_04.setObjectName("frame_kpis_04")
        self.gridLayout_2.addWidget(self.frame_kpis_04, 0, 3, 1, 1)
        self.frame_sales_overview = QtWidgets.QFrame(parent=WizardPage)
        self.frame_sales_overview.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_sales_overview.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_sales_overview.setObjectName("frame_sales_overview")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.frame_sales_overview)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(70, 30, 401, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_visualize = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_visualize.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_visualize.setObjectName("verticalLayout_visualize")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(parent=self.frame_sales_overview)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(580, 30, 401, 281))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_visualize_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_visualize_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_visualize_2.setObjectName("verticalLayout_visualize_2")
        self.gridLayout_2.addWidget(self.frame_sales_overview, 1, 0, 3, 4)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 1, 1, 1)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage"))
