# Form implementation generated from reading ui file 'E:\Ml_in_BA\Final\Sample_Architecture\SampleFinalProject\View\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(804, 356)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(20, 20, 601, 211))
        self.tableView.setObjectName("tableView")
        self.pushButtonCustomer = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCustomer.setGeometry(QtCore.QRect(20, 240, 81, 16))
        self.pushButtonCustomer.setObjectName("pushButtonCustomer")
        self.pushButtonEmployee = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonEmployee.setGeometry(QtCore.QRect(120, 240, 81, 16))
        self.pushButtonEmployee.setObjectName("pushButtonEmployee")
        self.pushButtonProduct = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonProduct.setGeometry(QtCore.QRect(220, 240, 56, 17))
        self.pushButtonProduct.setObjectName("pushButtonProduct")
        self.pushButtonSales = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSales.setGeometry(QtCore.QRect(300, 240, 56, 17))
        self.pushButtonSales.setObjectName("pushButtonSales")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 804, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonCustomer.setText(_translate("MainWindow", "Load Customer"))
        self.pushButtonEmployee.setText(_translate("MainWindow", "Load Employee"))
        self.pushButtonProduct.setText(_translate("MainWindow", "Load Product"))
        self.pushButtonSales.setText(_translate("MainWindow", "Load sales"))
