# Form implementation generated from reading ui file 'E:\Ml_in_BA\Final\MlInBA_FinalProject\View\OrderDetailWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from Controller.OrderDetailWizardController import OrderDetailWizardController
from Service.Base.TableService import TableViewService


class Ui_WizardPage(object):

    def __init__(self, additional_data):
        super().__init__()
        self.additional_data = additional_data

    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(715, 374)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=WizardPage)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 701, 361))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_customer_id = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_customer_id.setObjectName("lineEdit_customer_id")
        self.gridLayout.addWidget(self.lineEdit_customer_id, 1, 4, 1, 2)
        self.lineEdit_total = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_total.setObjectName("lineEdit_total")
        self.gridLayout.addWidget(self.lineEdit_total, 4, 3, 1, 3)
        self.label_total = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_total.setObjectName("label_total")
        self.gridLayout.addWidget(self.label_total, 4, 0, 1, 1)
        self.lineEdit_freight = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_freight.setObjectName("lineEdit_freight")
        self.gridLayout.addWidget(self.lineEdit_freight, 3, 3, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 2)
        self.label_freight = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_freight.setObjectName("label_freight")
        self.gridLayout.addWidget(self.label_freight, 3, 0, 1, 1)
        self.label_customer_id = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_customer_id.setObjectName("label_customer_id")
        self.gridLayout.addWidget(self.label_customer_id, 1, 3, 1, 1)
        self.label_order_id = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_order_id.setObjectName("label_order_id")
        self.gridLayout.addWidget(self.label_order_id, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 2)
        self.TableView = TableViewService(parent=self.gridLayoutWidget)
        self.TableView.setObjectName("TableView")
        self.gridLayout.addWidget(self.TableView, 2, 0, 1, 6)
        self.pushButton_close = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_close.setObjectName("pushButton_close")
        self.gridLayout.addWidget(self.pushButton_close, 5, 5, 1, 1)
        self.lineEdit_order_id = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_order_id.setObjectName("lineEdit_order_id")
        self.gridLayout.addWidget(self.lineEdit_order_id, 1, 1, 1, 2)
        self.label_page_name = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_page_name.setFont(font)
        self.label_page_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_page_name.setObjectName("label_page_name")
        self.gridLayout.addWidget(self.label_page_name, 0, 0, 1, 6)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)
        self.order_detail_controller = OrderDetailWizardController(self, WizardPage, self.additional_data)
        self.setup_data()
    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage"))
        self.label_total.setText(_translate("WizardPage", "Total:"))
        self.label_freight.setText(_translate("WizardPage", "Freight: "))
        self.label_customer_id.setText(_translate("WizardPage", "Customer ID"))
        self.label_order_id.setText(_translate("WizardPage", "Order ID:"))
        self.pushButton_close.setText(_translate("WizardPage", "Close"))
        self.label_page_name.setText(_translate("WizardPage", "Order Items"))

    def setup_data(self):
        self.lineEdit_customer_id.setText(str(self.additional_data['custId']))
        self.lineEdit_order_id.setText(str(self.additional_data['orderId']))
        self.lineEdit_freight.setText(str(self.additional_data['freight']))

        self.lineEdit_customer_id.setDisabled(True)
        self.lineEdit_order_id.setDisabled(True)
        self.lineEdit_freight.setDisabled(True)
        self.lineEdit_total.setDisabled(True)