# Form implementation generated from reading ui file 'E:\Ml_in_BA\Final\MlInBA_FinalProject\View\SalesPage.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from Service.SalesTableService import SalesTableService


class Ui_WizardSalesPage(object):
    def setupUi(self, WizardPage):
        WizardPage.setObjectName("WizardPage")
        WizardPage.resize(1060, 420)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=WizardPage)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 1061, 541))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_filter = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_filter.setObjectName("label_filter")
        self.gridLayout.addWidget(self.label_filter, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 6, 1, 1)
        self.lineEdit_filter = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.lineEdit_filter.setObjectName("lineEdit_filter")
        self.gridLayout.addWidget(self.lineEdit_filter, 0, 1, 1, 2)
        self.comboBox_filter = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.comboBox_filter.setObjectName("comboBox_filter")
        self.gridLayout.addWidget(self.comboBox_filter, 0, 3, 1, 2)

        self.TableView = SalesTableService(parent=self.gridLayoutWidget)
        self.TableView.setObjectName("TableView")
        self.gridLayout.addWidget(self.TableView, 1, 0, 1, 9)

        self.pushButton_view_items = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton_view_items.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton_view_items, 0, 5, 1, 1)

        self.retranslateUi(WizardPage)
        QtCore.QMetaObject.connectSlotsByName(WizardPage)

    def retranslateUi(self, WizardPage):
        _translate = QtCore.QCoreApplication.translate
        WizardPage.setWindowTitle(_translate("WizardPage", "WizardPage"))
        self.label_filter.setText(_translate("WizardPage", "Filter: "))
        self.lineEdit_filter.setPlaceholderText(_translate("WizardPage", "Insert filter content"))
        self.pushButton_view_items.setText(_translate("WizardPage", "View Items"))
